# Generated by Django 4.2.1 on 2023-05-07 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('eventId', models.AutoField(primary_key=True, serialize=False)),
                ('eventName', models.CharField(max_length=255)),
                ('eventDate', models.DateField()),
                ('eventTime', models.CharField(max_length=55)),
                ('isLiked', models.BooleanField(default=False)),
                ('location', models.CharField(max_length=255)),
                ('image', models.CharField(max_length=2555)),
            ],
        ),
    ]
