# Generated by Django 4.2.1 on 2023-05-07 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='isLiked',
        ),
        migrations.AddField(
            model_name='event',
            name='likedBY',
            field=models.JSONField(default=list),
        ),
    ]
