# Generated by Django 4.2.1 on 2023-05-08 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_value_remove_event_likedby_event_likedby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='value',
            name='value',
            field=models.IntegerField(null=True),
        ),
    ]
