# Generated by Django 4.2.1 on 2023-05-08 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_value_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='likedBY',
        ),
        migrations.DeleteModel(
            name='Value',
        ),
        migrations.AddField(
            model_name='event',
            name='likedBY',
            field=models.JSONField(default=list),
        ),
    ]
