# Generated by Django 4.2.1 on 2023-05-08 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_alter_event_likedby'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='likedBY',
        ),
        migrations.AddField(
            model_name='event',
            name='likedBy',
            field=models.JSONField(default=list),
        ),
    ]
